### ISSUE TITLE
Unable to build even after following instructions 

### ISSUE THREAD

**Issue by saurabhvyas** [skhu101/TDNN-F_NAS#1]
g++ version: 9.4.0

Kaldi version: [build] add nnet2online dependency to building nnet3bin. (#4749

Error:
nnet-utils.cc:1378:31: error: _bayestdnncomponent_ was not declared in this scope; did you mean _BayesTdnnV2Component_?

Did you compile it recently ?
If so, could you please mention kaldi and g++ version ?
Are you sure all code is present in the setup?

**Comment by skhu101** [comment]
Tanks for your comment. I forgot to delete the BayesTdnnComponent code here. You can delete the corresponding lines and recompile again. If there are any other problems, no hesitation to contact me.

**Comment by skhu101** [comment]
For the code in nnet-utils.cc, you can have a comparison with the Kaldi source code and only copy the code related with NAS component. I think the error should have nothing to do with gcc version. My gcc version is gcc-5.4.0.

**Comment by saurabhvyas** [comment]
Thanks for your reply, there were a few more components, I had to remove from the source code to fix those issues.

However, I am now getting the following error when compiling

nnet-simple-component.cc:5056:33: error: no matching function for call to ‘kaldi::CuMatrixBase<float>::ApplySoftMaxPerRow(kaldi::CuMatrix<float>&)’
 5056 |   out->ApplySoftMaxPerRow(output);

Any idea, how to resolve this ? 
Seems this one is related to Cuda, I have verified that source code is already compiled and kakdi test GPU available program is also running fine

**Comment by skhu101** [comment]
Sorry for the late reply. It seems that there is no definition for kaldi::CuMatrixBase::ApplySoftMaxPerRow. May I ask can you find the function in nnet-simple-component.cc?

**Comment by saurabhvyas** [comment]
Sorry even I got busy and started working on another project, I am closing this one for now, but appreciate your help.

**Comment by skhu101** [comment]
Hello, I have compiled the files in the newest Kaldi and find your mentioned ApplySoftMaxPerRow error is due to that in the updated Kaldi version ApplySoftMaxPerRow is renamed to SoftMaxPerRow. If you have further errors, I am happy to discuss. My successful recompiled Kaldi files with our NAS code is also putting on the Google Drive.
